// AUTO-GENERATED by scripts/gen-reserved-paths.mjs — do not edit by hand.
// Run `pnpm --filter admin gen:reserved-paths` to refresh.
// First URL segments already used by real pages in apps/web. A live-course
// custom path may not start with any of these.
export const RESERVED_FIRST_SEGMENTS: readonly string[] = [
  "about",
  "api",
  "blog",
  "c",
  "cart",
  "certificate",
  "checkout",
  "contact",
  "courses",
  "dashboard",
  "faq",
  "fonts",
  "forgot-password",
  "free-courses",
  "guest",
  "join-as-instructor",
  "learn",
  "live-classes",
  "login",
  "maintenance",
  "notifications",
  "our-instructor",
  "privacy-policy",
  "return-policy",
  "shop",
  "signup",
  "student",
  "success-stories",
  "terms-conditions",
  "verify"
];
