export const GENERAL_KEYS = [
  "general_site_name",
  "general_tagline",
  "general_meta_description",
  "general_logo_url",
  "general_logo_url_dark",
  "general_favicon_url",
  "general_contact_email",
  "general_contact_phone",
  "general_contact_phone2",
  "general_support_whatsapp",
  "general_address",
  "general_copyright",
  "general_trade_license",
  "general_cta_enroll",
  "general_cta_enroll_free",
  "general_cta_continue",
  "general_dash_go_to_class",
  "general_dash_start_learning",
  "general_dash_continue",
  "general_dash_review",
  "general_admin_accent_color",
  "general_timezone",
  "general_date_format",
  "general_time_format",
  "general_company_name",
  "general_business_country",
  "general_business_state",
  "general_business_postal_code",
  "general_vat_tin_bin",
  "general_registration_certificate_url",
  "general_english_font",
  "general_bangla_font",
] as const;

export type GeneralSettingsKey = (typeof GENERAL_KEYS)[number];

export type GeneralSettings = Record<GeneralSettingsKey, string>;

export const GENERAL_DEFAULTS: GeneralSettings = {
  general_site_name:     "",
  general_tagline:       "",
  general_meta_description: "",
  general_logo_url:      "",
  general_logo_url_dark: "",
  general_favicon_url:   "",
  general_contact_email:     "",
  general_contact_phone:     "",
  general_contact_phone2:    "",
  general_support_whatsapp:  "",
  general_address:            "",
  general_copyright:       "",
  general_trade_license:   "",
  general_cta_enroll:        "",
  general_cta_enroll_free:   "",
  general_cta_continue:      "",
  general_dash_go_to_class:    "",
  general_dash_start_learning: "",
  general_dash_continue:       "",
  general_dash_review:         "",
  general_admin_accent_color: "#a64dff",
  general_timezone:    "Asia/Dhaka",
  general_date_format: "dd_mmm_yyyy",
  general_time_format: "12h",
  general_company_name:                  "",
  general_business_country:              "",
  general_business_state:                "",
  general_business_postal_code:          "",
  general_vat_tin_bin:                   "",
  general_registration_certificate_url:  "",
  general_english_font:  "Poppins",
  general_bangla_font:   "Hind Siliguri",
};
